---
title: "Google Trends Report"
author: "Rodolfo Terra"
date: "`r lubridate::now()`"
output: 
  html_document:
    theme: flatly
  pdf_document: default
params:
  search_terms: !r c("aws", "azure"," google cloud")
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE
)

# Google Trends API
library(gtrendsR)

# Core ----
library(tidyverse)
library(lubridate)
library(tidyquant)

# File System
library(fs)

```

# Report Search Terms

```{r} 

tibble("Search Terms" = params$search_terms %>% knitr::kable())

```

```{r} 

gtrends_lst <- gtrendsR::gtrends(params$search_terms,geo = 'US', time ='all')

```

# Trends Over Time

```{r} 
gtrends_lst %>%
  pluck("interest_over_time") %>%
  mutate(hits = as.numeric(hits)) %>%
  as_tibble() %>%
  ggplot(aes(date, hits, color =  keyword)) +
  geom_line() +
  geom_smooth(sapn = 0.3, se = TRUE) +
  theme_tq() +
  scale_color_tq() +
  labs(title = "Keyword Trends - US - Over Time")

```

# Trends By Geography


```{r, fig.height = 3} 

states_tbl <- map_data("state") %>%
  as_tibble() %>%
  mutate(region = str_to_title(region))

state_trends_tbl <- gtrends_lst %>%
  pluck("interest_by_region") %>%
  left_join(states_tbl, by = c('location' = "region")) %>%
  as_tibble()

state_trends_tbl %>%
  ggplot(aes(long, lat)) +
  geom_polygon(aes(group = group, fill= hits)) +
  coord_map("albers", at0=45.5, last1 = 29.5) +
  scale_fill_viridis_c() +
  theme_tq() +
  facet_wrap(~keyword,  nrow = 1) +
  labs(title = "Keyword Trends - US")

```

# Top Related Searches


```{r} 

n_terms <- 20

top_n_related_searches_tbl <- gtrends_lst %>%
  pluck("related_queries") %>%
  as_tibble() %>%
  filter(related_queries == "top") %>%
  mutate(interest = as.numeric(subject)) %>%
  
  select(keyword, value, interest) %>%
  group_by(keyword) %>%
  arrange(desc(interest)) %>%
  slice(1:n_terms) %>%
  ungroup() %>%
  
  mutate(value = as_factor(value) %>% fct_reorder(interest))


top_n_related_searches_tbl %>%
  ggplot(aes(value, interest, color = keyword)) +
  geom_segment(aes(xend = value, yend = 0)) +
  geom_point() +
  coord_flip() +
  facet_wrap(~ keyword, nrow = 1, scales = "free_y") +
  theme_tq() +
  scale_color_tq()


```













